'use strict';
const KEY='jugglerMultiData_v9', V=9;
const CORE=[['grape','small','ぶどう'],['cherry','small','チェリー'],['solo_bb','BB','単独BIG'],['cherry_bb','BB','チェリーBIG'],['solo_rb','RB','単独REG'],['cherry_rb','RB','チェリーREG']].map(([key,category,name])=>({id:'core-'+key,key,category,name,count:0}));
let specs=[],chart=null,state=root(),countMode='add',editingCounterId=null;
const $=id=>document.getElementById(id), N=v=>Math.max(0,parseInt(v,10)||0), C=x=>JSON.parse(JSON.stringify(x));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function game(){return {series:'マイジャグラーV',machineNo:'',sessionStarted:false,startSnapshot:{totalGames:0,bb:0,rb:0,currentGames:0},totalGames:0,lastBonusTotalGame:0,counters:CORE.map(x=>({...x})),history:[],actionHistory:[]};}
function root(){return {version:V,currentTab:'A',analysisMode:'machine',dark:false,appData:{A:game(),B:game(),C:game()}};}
function d(){return state.appData[state.currentTab];}
function session(x=d()){return Math.max(0,x.totalGames-x.startSnapshot.totalGames);}
function hasSessionStarted(x=d()){return !!x.sessionStarted||session(x)>0||x.counters.some(c=>c.count>0)||x.history.length>0;}
function isCoreCounter(c){return CORE.some((core,i)=>core.key===c.key||core.name===c.name||String(core.id)===String(c.id)||String(i+1)===String(c.id));}
function normalizeCounters(x){const all=Array.isArray(x.counters)?x.counters:[];x.counters=CORE.map((core,i)=>{const f=all.find(c=>c.key===core.key||String(c.id)===String(core.id)||String(c.id)===String(i+1)||c.name===core.name);return {...core,name:String(f?.name||core.name).slice(0,30),count:N(f?.count)};}).concat(all.filter(c=>!isCoreCounter(c)).map((c,i)=>({id:String(c.id||'custom-'+i),key:String(c.key||'custom_'+i),category:['BB','RB','small'].includes(c.category)?c.category:'custom',name:String(c.name||'項目').slice(0,30),count:N(c.count)})));}
function normalizeGames(x){normalizeCounters(x);x.startSnapshot=Object.assign(game().startSnapshot,x.startSnapshot||{});x.startSnapshot.totalGames=N(x.startSnapshot.totalGames);x.startSnapshot.bb=N(x.startSnapshot.bb);x.startSnapshot.rb=N(x.startSnapshot.rb);x.startSnapshot.currentGames=Math.min(N(x.startSnapshot.currentGames),x.startSnapshot.totalGames);x.totalGames=Math.max(N(x.totalGames),x.startSnapshot.totalGames);x.lastBonusTotalGame=Math.min(x.totalGames,Math.max(0,N(x.lastBonusTotalGame)));return x;}
function migrate(raw){const x=Object.assign(game(),raw||{});x.startSnapshot=Object.assign(game().startSnapshot,raw?.startSnapshot||raw?.snapshot||{});const old=raw?.currentGames;x.totalGames=N(x.totalGames);x.counters=Array.isArray(raw?.counters)?raw.counters:[];x.history=Array.isArray(raw?.history)?raw.history:(raw?.history?.session||[]);x.lastBonusTotalGame=Number.isFinite(Number(raw?.lastBonusTotalGame))?N(raw.lastBonusTotalGame):Math.max(0,x.startSnapshot.totalGames-N(x.startSnapshot.currentGames||old));x.sessionStarted=typeof raw?.sessionStarted==='boolean'?raw.sessionStarted:hasSessionStarted(x);x.actionHistory=[];return normalizeGames(x);}
function load(){try{const raw=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('jugglerMultiData_v8')||localStorage.getItem('jugglerMultiData_v7')||localStorage.getItem('jugglerMultiData_v6')||localStorage.getItem('jugglerMultiData_v5')||'null');if(!raw)return;state=root();state.currentTab=['A','B','C'].includes(raw.currentTab)?raw.currentTab:'A';state.analysisMode=raw.analysisMode==='session'?'session':'machine';state.dark=!!(raw.dark??raw.isDark);['A','B','C'].forEach(k=>state.appData[k]=migrate(raw.appData?.[k]));}catch(e){console.warn('load',e);}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));$('save-status').textContent='✓ 自動保存済み';$('counter-note').textContent=state.analysisMode==='machine'?'着席前の内訳が不明なため各カウント確率は「—」で表示します。':'各カウントの確率は自分の実戦Gで計算します。';}
function nowG(x=d()){return Math.max(0,x.totalGames-x.lastBonusTotalGame);}
function cat(category,x=d()){return x.counters.filter(c=>c.category===category).reduce((s,c)=>s+c.count,0);}
function byKey(key,x=d()){return x.counters.find(c=>c.key===key)?.count||0;}
function p(g,c){return g&&c?'1/'+(g/c).toFixed(2):'1/---';}
function met(mode=state.analysisMode,x=d()){const bb=cat('BB',x),rb=cat('RB',x);return mode==='machine'?{g:x.totalGames,bb:x.startSnapshot.bb+bb,rb:x.startSnapshot.rb+rb}:{g:session(x),bb,rb};}
function snap(){const x=d();return {totalGames:x.totalGames,lastBonusTotalGame:x.lastBonusTotalGame,counters:C(x.counters),history:C(x.history)};}
function restore(s){const x=d();x.totalGames=s.totalGames;x.lastBonusTotalGame=s.lastBonusTotalGame;x.counters=s.counters;x.history=s.history;normalizeGames(x);}
function record(){const x=d(),g=session(x);if(!g)return;const q={totalGames:x.totalGames,sessionGames:g,grape:byKey('grape',x)?g/byKey('grape',x):null,sessionBB:cat('BB',x),sessionRB:cat('RB',x),wholeBB:x.startSnapshot.bb+cat('BB',x),wholeRB:x.startSnapshot.rb+cat('RB',x),timestamp:new Date().toISOString()};const last=x.history.at(-1);if(last&&last.totalGames===q.totalGames)x.history[x.history.length-1]=q;else x.history.push(q);if(x.history.length>500)x.history.shift();}
function commit(fn,history=true){const x=d();x.actionHistory.push(snap());if(x.actionHistory.length>150)x.actionHistory.shift();fn(x);normalizeGames(x);if(history)record();save();render();}
let tintTimer=null,statusTimer=null;
function feedback(mode,card,changed=true){if(!changed)return;const overlay=$('tap-flash');overlay.classList.remove('add','subtract','visible');document.body.classList.add('feedback-frame');$('tap-status').textContent=mode==='add'?'＋1':'－1';if(card)card.classList.remove('feedback-add','feedback-subtract');void overlay.offsetWidth;overlay.classList.add(mode,'visible');if(card)card.classList.add(mode==='add'?'feedback-add':'feedback-subtract');clearTimeout(tintTimer);clearTimeout(statusTimer);tintTimer=setTimeout(()=>{overlay.classList.remove('visible','add','subtract');document.body.classList.remove('feedback-frame');},130);statusTimer=setTimeout(()=>{$('tap-status').textContent='';if(card)card.classList.remove('feedback-add','feedback-subtract');},350);}
function tap(id,card){const mode=countMode;let changed=false;commit(x=>{const c=x.counters.find(q=>q.id===id);if(!c)return;if(mode==='subtract'){if(c.count>0){c.count--;changed=true;}}else{c.count++;changed=true;if(c.category==='BB'||c.category==='RB')x.lastBonusTotalGame=x.totalGames;}});feedback(mode,card,changed);}
function undo(){const s=d().actionHistory.pop();if(!s)return;restore(s);save();render();feedback('subtract',null,true);}
function resetSessionData(x,started){x.startSnapshot={totalGames:0,bb:0,rb:0,currentGames:0};x.totalGames=0;x.lastBonusTotalGame=0;x.counters.forEach(c=>c.count=0);x.history=[];x.actionHistory=[];x.sessionStarted=started;}
function saveSnapshot(){const x=d(),total=N($('start-total-input').value),current=Math.min(N($('start-current-input').value),total),started=hasSessionStarted(x),hasBonus=cat('BB',x)+cat('RB',x)>0;x.startSnapshot={totalGames:total,bb:N($('start-bb-input').value),rb:N($('start-rb-input').value),currentGames:current};if(!started){x.totalGames=total;x.history=[];}if(!hasBonus)x.lastBonusTotalGame=total-current;x.sessionStarted=true;countMode='add';normalizeGames(x);save();render();$('snapshot-dialog').close();}
function saveTotal(){const value=Math.max(N($('total-edit-input').value),d().startSnapshot.totalGames),current=nowG();if(value<current){$('total-edit-error').hidden=false;return;}commit(x=>{x.totalGames=value;x.lastBonusTotalGame=value-current;},false);$('total-dialog').close();}
function saveCurrent(){const v=N($('current-edit-input').value);if(v>d().totalGames){$('current-edit-error').hidden=false;return;}commit(x=>x.lastBonusTotalGame=x.totalGames-v,false);$('current-dialog').close();}
function rates(values){return values.map(v=>1/v);}
function monotonic(values){const r=rates(values);return r.every((v,i)=>!i||v>=r[i-1])||r.every((v,i)=>!i||v<=r[i-1]);}
function badge(current,values){if(!current||!monotonic(values))return '';const r=rates(values),cr=1/current,low=Math.min(...r),high=Math.max(...r),first=r.indexOf(low),last=r.indexOf(high);if(cr<low)return '<span class="badge">設定'+(first+1)+'未満</span>';if(cr>=high)return '<span class="badge">設定'+(last+1)+'基準以上</span>';let i=0;for(;i<5&&cr>=r[i+1];i++);return '<span class="badge">設定'+(i+1)+'基準以上</span>';}
function groups(values,decimals){const map=new Map();values.forEach((v,i)=>{const key=v.toFixed(decimals);if(!map.has(key))map.set(key,[]);map.get(key).push(i+1);});return [...map.entries()].map(([key,ids])=>`<span class="parameter-label" style="left:${parameterScale(Number(key),values)}%"><b>設${ids.join('・')}</b><small>1/${key}</small></span>`).join('');}
function parameterScale(denominator,values){const r=rates(values),lo=Math.min(...r),hi=Math.max(...r);return hi===lo?50:((1/denominator-lo)/(hi-lo))*100;}
function parameter(name,current,values,note){if(!values?.length)return '';const dec=name==='ぶどう'?2:1,base=values.map(v=>'1/'+v.toFixed(dec)).join(' / ');if(!monotonic(values))return `<div class="parameter"><strong>${name}</strong>　${current?'1/'+current.toFixed(2):'<span class="unavailable">'+(note==='算出不可'?'算出不可':'-')+'</span>'}<br><small>${current?'単純比較不可':'算出不可'} / 各設定値を一覧表示</small><div class="parameter-fallback">${base}</div></div>`;const r=rates(values),lo=Math.min(...r),hi=Math.max(...r),cr=current?1/current:null,pos=cr===null?null:Math.max(0,Math.min(100,hi===lo?50:((cr-lo)/(hi-lo))*100)),markers=values.map(v=>`<i style="left:${parameterScale(v,values)}%"></i>`).join('');return `<div class="parameter"><strong>${name}</strong>　${current?'現在 1/'+current.toFixed(2)+' '+badge(current,values):'<span class="unavailable">'+(note==='算出不可'?'算出不可':'-')+'</span>'}<div class="parameter-track">${markers}${pos===null?'':`<b style="left:${pos}%">▲</b>`}</div><div class="parameter-labels">${groups(values,dec)}</div></div>`;}
function comparisonHtml(){const x=d(),s=specs.find(q=>q.name===x.series),machine=state.analysisMode==='machine',m=met(state.analysisMode),own=met('session');if(!s)return '<p class="parameter-note">実測値と設定別基準値の比較です。実際の設定を断定するものではありません。</p>';return '<p class="parameter-note">実測値と設定別基準値の比較です。実際の設定を断定するものではありません。</p>'+parameter('ぶどう',machine?null:(byKey('grape',x)?own.g/byKey('grape',x):null),s.grape,machine?'算出不可':'自分の実戦')+parameter('ボーナス合算',m.bb+m.rb?m.g/(m.bb+m.rb):null,s.total,machine?'台全体':'自分の実戦')+parameter('合算BIG',m.bb?m.g/m.bb:null,s.bb,machine?'台全体':'自分の実戦')+parameter('合算REG',m.rb?m.g/m.rb:null,s.rb,machine?'台全体':'自分の実戦')+parameter('単独BIG',machine?null:(byKey('solo_bb',x)?own.g/byKey('solo_bb',x):null),s.solo_bb,machine?'算出不可':'自分の実戦')+parameter('単独REG',machine?null:(byKey('solo_rb',x)?own.g/byKey('solo_rb',x):null),s.solo_rb,machine?'算出不可':'自分の実戦');}
function settings(){const x=d();$('series-input').replaceChildren(...specs.map(s=>{const o=document.createElement('option');o.value=s.name;o.textContent=s.name;o.selected=x.series===s.name;return o;}));$('machine-input').value=x.machineNo;$('start-total-input').value=x.startSnapshot.totalGames;$('start-bb-input').value=x.startSnapshot.bb;$('start-rb-input').value=x.startSnapshot.rb;$('start-current-input').value=x.startSnapshot.currentGames;const row=c=>`<div class="setting-counter"><label>${esc(c.name)}<input data-count="${esc(c.id)}" value="${c.count}" inputmode="numeric"></label><button type="button" data-name="${esc(c.id)}">名称</button>${isCoreCounter(c)?'<span></span>':`<button type="button" class="remove" data-del="${esc(c.id)}">削除</button>`}</div>`;$('counter-settings').innerHTML='<h3>基本カウンター（順番固定）</h3>'+x.counters.filter(isCoreCounter).map(row).join('')+'<h3>カスタム項目</h3>'+x.counters.filter(c=>!isCoreCounter(c)).map(row).join('');}
function render(){const x=d(),own=met('session'),active=met(state.analysisMode),machine=state.analysisMode==='machine';document.body.classList.toggle('dark',state.dark);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.currentTab));document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.analysisMode));$('machine-label').textContent=x.series;$('machine-number').textContent=x.machineNo?'台番号 '+x.machineNo:'台番号 未入力';$('start-card').hidden=x.sessionStarted;$('counter-note').textContent=machine?'着席前の内訳が不明なため各カウント確率は「—」で表示します。':'各カウントの確率は自分の実戦Gで計算します。';$('snapshot-summary').hidden=!x.sessionStarted;$('snapshot-text').textContent=`着席 ${x.startSnapshot.totalGames}G / B${x.startSnapshot.bb} / R${x.startSnapshot.rb} / 現在${x.startSnapshot.currentGames}G`;$('total-display').textContent=x.totalGames+' G';$('current-display').textContent=nowG(x)+' G';$('agg-bb').textContent=p(active.g,active.bb);$('agg-rb').textContent=p(active.g,active.rb);$('agg-total').textContent=p(active.g,active.bb+active.rb);$('undo-button').disabled=!x.actionHistory.length;$('add-mode').classList.toggle('active',countMode==='add');$('subtract-mode').classList.toggle('subtract-active',countMode==='subtract');const card=c=>{const box=document.createElement('div');box.className='counter-card';const main=document.createElement('button');main.className='counter counter-main';main.dataset.tap=c.id;main.setAttribute('aria-label',`${c.name}を${countMode==='add'?'加算':'減算'}`);main.innerHTML=`<span>${esc(c.name)}</span><b>${c.count}</b><small>確率 ${machine?'—':p(own.g,c.count)}</small>`;const edit=document.createElement('button');edit.className='counter-edit';edit.dataset.editCard=c.id;edit.setAttribute('aria-label',c.name+'を編集');edit.textContent='✎';box.append(main,edit);return box;};$('counter-grid').replaceChildren(...CORE.map(core=>card(x.counters.find(q=>q.key===core.key))));const custom=x.counters.filter(c=>!isCoreCounter(c));$('custom-grid').replaceChildren(...custom.map(card));$('custom-section').hidden=!custom.length;if(custom.length)$('custom-summary').textContent='追加項目（'+custom.length+'）';$('main-compare-content').innerHTML=comparisonHtml();settings();}
function spec(){const s=specs.find(q=>q.name===d().series);if(!s)return;$('spec-title').textContent='📖 '+s.name+' スペック一覧';$('spec-content').innerHTML='<table><tr><th>設定</th><th>ぶどう</th><th>単独BIG</th><th>合算BIG</th><th>単独REG</th><th>合算REG</th><th>合算</th></tr>'+s.grape.map((_,i)=>`<tr><td>${i+1}</td><td>1/${s.grape[i].toFixed(2)}</td><td>1/${s.solo_bb[i].toFixed(1)}</td><td>1/${s.bb[i].toFixed(1)}</td><td>1/${s.solo_rb[i].toFixed(1)}</td><td>1/${s.rb[i].toFixed(1)}</td><td>1/${s.total[i].toFixed(1)}</td></tr>`).join('')+'</table>';$('spec-dialog').showModal();}
function graph(){if(typeof Chart==='undefined')return alert('グラフ機能を読み込めません。');const x=d(),h=x.history.filter(q=>q.sessionGames>=100),own=state.analysisMode==='session';if(chart)chart.destroy();const ds=own?[['ぶどう','grape','#34c759'],['REG','sessionRB','#007aff']]:[['台全体 BIG','wholeBB','#ff3b30'],['台全体 REG','wholeRB','#007aff'],['台全体 合算','total','#ff9500']];chart=new Chart($('prob-chart'),{type:'line',data:{datasets:ds.map(([label,key,color])=>({label,data:h.map(q=>({x:own?q.sessionGames:q.totalGames,y:key==='grape'?q.grape:key==='sessionRB'?(q.sessionRB?q.sessionGames/q.sessionRB:null):key==='wholeBB'?(q.wholeBB?q.totalGames/q.wholeBB:null):key==='wholeRB'?(q.wholeRB?q.totalGames/q.wholeRB:null):(q.wholeBB+q.wholeRB?q.totalGames/(q.wholeBB+q.wholeRB):null)})),borderColor:color}))},options:{responsive:true,maintainAspectRatio:false,scales:{x:{type:'linear'},y:{title:{display:true,text:'確率（1/◯）'}}}}});$('graph-note').textContent=own?'自分の実戦開始後の推移です。':'台全体BIG・REG・合算の推移です。';$('graph-dialog').showModal();}
function onClick(e){const b=e.target.closest('button');if(!b)return;if(b.dataset.tap)return tap(b.dataset.tap,b);if(b.dataset.tab){state.currentTab=b.dataset.tab;countMode='add';save();return render();}if(b.dataset.mode){state.analysisMode=b.dataset.mode;save();return render();}if(b.dataset.games)return commit(x=>x.totalGames=Math.max(x.startSnapshot.totalGames,x.totalGames+Number(b.dataset.games)));if(b.id==='settings-open')return $('settings-dialog').showModal();if(b.id==='theme-toggle'){state.dark=!state.dark;save();return render();}if(b.id==='add-mode'||b.id==='subtract-mode'){countMode=b.id==='add-mode'?'add':'subtract';return render();}if(b.id==='undo-button')return undo();if(b.id==='start-zero'){resetSessionData(d(),true);countMode='add';save();return render();}if(b.id==='start-mid'||b.id==='snapshot-edit')return $('snapshot-dialog').showModal();if(b.id==='snapshot-save')return saveSnapshot();if(b.id==='total-display'||b.id==='total-edit'){$('total-edit-input').value=d().totalGames;$('total-edit-error').hidden=true;return $('total-dialog').showModal();}if(b.id==='total-edit-save')return saveTotal();if(b.id==='current-display'||b.id==='current-edit'){$('current-edit-input').value=nowG();$('current-edit-error').hidden=true;return $('current-dialog').showModal();}if(b.id==='current-edit-save')return saveCurrent();if(b.dataset.editCard){editingCounterId=b.dataset.editCard;const c=d().counters.find(q=>q.id===editingCounterId);$('count-dialog-title').textContent=c.name+'の回数';$('count-edit-input').value=c.count;$('count-edit-error').hidden=true;return $('count-dialog').showModal();}if(b.id==='count-edit-save'){const v=$('count-edit-input').value;if(!/^\d+$/.test(v))return $('count-edit-error').hidden=false;commit(x=>x.counters.find(q=>q.id===editingCounterId).count=N(v));return $('count-dialog').close();}if(b.id==='add-counter'){const name=prompt('追加する項目の名称を入力してください');if(name?.trim())return commit(x=>x.counters.push({id:'custom-'+Date.now(),key:'custom_'+Date.now(),category:'custom',name:name.trim().slice(0,30),count:0}));}if(b.id==='reset-button'&&confirm('現在の台データをリセットしますか？')){resetSessionData(d(),false);save();render();}if(b.dataset.open==='graph')return graph();if(b.dataset.open==='spec')return spec();}
function onChange(e){if(e.target.id==='series-input')return commit(x=>x.series=e.target.value);if(e.target.id==='machine-input')return commit(x=>x.machineNo=e.target.value.slice(0,30));if(e.target.dataset.count)return commit(x=>x.counters.find(q=>q.id===e.target.dataset.count).count=N(e.target.value));}
async function init(){load();try{specs=await fetch('./data/juggler-specs.json').then(r=>r.json());}catch(e){console.warn('specs',e);}if(!specs.length)specs=[{name:'マイジャグラーV',grape:[5.9,5.85,5.8,5.75,5.7,5.66],bb:[273.1,270.8,266.4,254,240.9,229.1],rb:[409.6,385.5,336.1,290,268.6,229.1],total:[163.8,159.1,148.6,135.4,127,114.6],solo_bb:[402,394.8,381,358.1,334.3,318.1],solo_rb:[564.9,528.5,442.8,368.1,334.3,277.6]}];document.addEventListener('click',onClick);document.addEventListener('change',onChange);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();}
init();
